
    create table alimentazione (
        id integer generated by default as identity,
        descrizione varchar(255) not null unique,
        primary key (id)
    );

    create table alimentazione_tipo_veicolo (
        alimentazione_id integer not null,
        tipo_veicolo_id integer not null
    );

    create table bici (
        freno_id integer,
        id_bici integer generated by default as identity,
        nr_ruote integer not null,
        numero_marce integer not null,
        pieghevole boolean,
        sospensione_id integer,
        veicolo_id integer unique,
        primary key (id_bici)
    );

    create table categoria (
        id integer generated by default as identity,
        descrizione varchar(255) not null unique,
        primary key (id)
    );

    create table categoria_tipo_veicolo (
        categoria_id integer not null,
        tipo_veicolo_id integer not null
    );

    create table freno (
        id integer generated by default as identity,
        descrizione varchar(255) not null unique,
        primary key (id)
    );

    create table macchina (
        cc integer,
        id_auto integer generated by default as identity,
        numero_porte integer,
        numero_ruote integer,
        veicolo_id integer unique,
        targa varchar(7) not null unique,
        primary key (id_auto)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table moto (
        cc integer not null,
        id_moto integer generated by default as identity,
        numero_ruote integer not null,
        veicolo_id integer unique,
        targa varchar(100) not null,
        primary key (id_moto)
    );

    create table sospensione (
        id integer generated by default as identity,
        descrizione varchar(255) not null unique,
        primary key (id)
    );

    create table tipo_veicolo (
        id integer generated by default as identity,
        nome varchar(255) not null unique,
        primary key (id)
    );

    create table veicolo (
        alimentazione_id integer,
        anno_produzione integer,
        categoria_id integer,
        id_veicolo integer generated by default as identity,
        tipo_veicolo_id integer,
        colore varchar(100) not null,
        marca varchar(100) not null,
        modello varchar(100) not null,
        primary key (id_veicolo)
    );

    alter table if exists alimentazione_tipo_veicolo 
       add constraint FK5fk8b2jheou7sgaywj91i6tfh 
       foreign key (tipo_veicolo_id) 
       references tipo_veicolo;

    alter table if exists alimentazione_tipo_veicolo 
       add constraint FKpcf7h8lsonsihtkekf9nrr5pf 
       foreign key (alimentazione_id) 
       references alimentazione;

    alter table if exists bici 
       add constraint FKbws1i3mir17a05465g0hcpq2b 
       foreign key (freno_id) 
       references freno;

    alter table if exists bici 
       add constraint FK5w8050dk24bill0p1oybx526d 
       foreign key (sospensione_id) 
       references sospensione;

    alter table if exists bici 
       add constraint FKi5oid68i9rxxblvmtn9m2o23h 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists categoria_tipo_veicolo 
       add constraint FK4qphatkdao1ybsbj3rj1je3xe 
       foreign key (tipo_veicolo_id) 
       references tipo_veicolo;

    alter table if exists categoria_tipo_veicolo 
       add constraint FKl9tpa4n16jptbe2r32wkydpqd 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists macchina 
       add constraint FKoelgn029d5si9n8nlgjai441m 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists moto 
       add constraint FK8bspqpxxs5e6umxpiktmxolv0 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists veicolo 
       add constraint FK2vsaxu42kao1fd973kjeegsud 
       foreign key (alimentazione_id) 
       references alimentazione;

    alter table if exists veicolo 
       add constraint FK1ffq24yvhb1147soqdmhcrr75 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists veicolo 
       add constraint FKc2pjr19k42ngy56jq4xo1h246 
       foreign key (tipo_veicolo_id) 
       references tipo_veicolo;
