veicolo.selectByFilter= select v from Veicolo v \
left join v.macchina m \
left join v.moto mo \
where (:tipoVeicolo is null or v.tipoVeicolo.nome like concat(cast(:tipoVeicolo as text),'%')) \
and (:colore is null or v.colore like concat(cast(:colore as text),'%')) \
and (:alimentazione is null or v.alimentazione.descrizione like concat(cast(:alimentazione as text),'%')) \
and (:categoria is null or v.categoria.descrizione like concat(cast(:categoria as text),'%')) \
and (:targa is null or m.targa like concat(cast(:targa as text),'%') or mo.targa like concat(cast(:targa as text),'%')) \
and (:idVeicolo is null or v.idVeicolo = :idVeicolo) 


	
